### ISSUE TITLE
no case clause matching: [] during redirect scenario

### ISSUE THREAD

**Issue by cpursley** [gushonorato/mechanizex#36]
Nice library!

I've been try to track down the cause of this issue with no luck. Any ideas?

```
2022-08-14 17:59:31.816 [error] GenServer #PID<0.1271.0> terminating
** (CaseClauseError) no case clause matching: []
    (hackney 1.18.1) my-app/hackney/src/hackney_url.erl:248: :hackney_url.parse_netloc/2
    (hackney 1.18.1) my-app/hackney/src/hackney.erl:351: :hackney.request/5
    (httpoison 1.8.2) lib/httpoison/base.ex:846: HTTPoison.Base.request/6
    (mechanize 0.1.0) lib/mechanize/http_adapter/httpoison.ex:151: Mechanize.HTTPAdapter.Httpoison.request!/1
    (mechanize 0.1.0) lib/mechanize/browser/impl.ex:125: Mechanize.Browser.Impl.request!/3
    (mechanize 0.1.0) lib/mechanize/browser/impl.ex:169: Mechanize.Browser.Impl.follow_redirect/4
    (mechanize 0.1.0) lib/mechanize/browser/impl.ex:74: Mechanize.Browser.Impl.request!/2
    (mechanize 0.1.0) lib/mechanize/browser/server.ex:68: Mechanize.Browser.Server.handle_call/3
    (stdlib 3.17.2) gen_server.erl:721: :gen_server.try_handle_call/4
    (stdlib 3.17.2) gen_server.erl:750: :gen_server.handle_msg/6
    (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.1266.0>): {:request!, %Mechanize.Request{body: "", headers: [], method: :get, options: [], params: [], url: "https://someurl.com/?redirect=true"}}
```

**Comment by gushonorato** [comment]
Hello @cpursley

Can you provide me with some more context?

Which version of Elixir are you using?
What is the URL you are issuing this GET request? 
Is it failing with this URL or is the error occurring when you try others URLs?

Cheers,

**Comment by cpursley** [comment]
I'll close for now but will let you know if I can reproduce. Thank you.
